#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#  jackson:
#    property-naming-strategy: SNAKE_CASE
#
#custom:
#  pageable:
#    offset: 0
#    limit: 10

spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: been
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
  profiles:
    include: oauth
    session:
      store-type: jdbc
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          google:
            client-id: 647531838686-2q61sja6ohnr93r0dgfvrffpu4sld37a.apps.googleusercontent.com
            client-secret: 4YknZSW6ZB6QcSwVRPJgkgDq
            scope: profile,email
          naver:
            authorization-grant-type: authorization_code
            client-id: 8_vqEyDIN3JBx64B1Wb8
            client-name: Naver
            client-secret: p6RbUFhYwj
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: name,email,profile_image

custom:
  pageable:
    offset: 0
    limit: 10